# main:
#   - identifier: "about"
#     name: "About"
#     url: "/about"
#     weight: -1
#     params:
#       icon: "user"
#       newtab: true

social:
  - identifier: "github"
    name: "GitHub"
    weight: 1
    url: "https://github.com/shivangjhalani"
    params:
      icon: "brand-github"

  - identifier: "linkedin"
    weight: 2
    name: "Linkedin"
    url: "https://www.linkedin.com/in/shivang-jhalani/"
    params:
      icon: "brand-linkedin"
  
  - identifier: "twitter"
    weight: 3
    name: "Twitter"
    url: "https://x.com/jhalani_shivang"
    params:
      icon: "brand-twitter"

  - identifier: "rss"
    name: "RSS"
    url: "/index.xml"
    params:
      icon: "rss"
