//------------------------------------------------------------------------------
// Module: sap1_cpu_top (Modified for ALU, Step/Run, Live Display)
// Description: SAP-1 CPU Top-Level Module with ALU, 7-Segment Display Output,
//              and Step/Run control.
//------------------------------------------------------------------------------
module sap1_cpu_top (
    input         clk_in,     // Clock input (Connect to Basys 3 100MHz oscillator)
    input         rst,        // Reset input (Connect to BTNC or reset circuit)
    input         btn_step,   // Step Clock Button (Connect to BTNR T17)
    input         btn_run,    // Run Clock Button (Connect to BTND U17)

    output        hlt_out,    // Output the halt signal status (e.g., to an LED)

    // Outputs for the 7-Segment Display
    output [6:0]  seg_out,    // Segment cathodes (Active LOW)
    output [3:0]  an_out      // Anode selectors (Active LOW)
);

    // --- Internal Signal Declarations ---

    // Clocks and Reset
    wire cpu_clk;   // Clock generated by the clock module (gated/pulsed)
    wire hlt;       // Internal halt signal from controller (latched)

    // Control Signals (Expanded for ALU)
    wire pc_inc;
    wire pc_en;
    wire mar_load;
    wire mem_en;
    wire ir_load;
    wire ir_en;
    wire a_load;
    wire a_en;
    wire b_load;
    wire alu_en;
    wire [2:0] alu_op_sel;
    wire [13:0] control_word;

    // Data Paths & Intermediate Signals
    wire [7:0] bus_data;
    wire [3:0] pc_out_internal;
    wire [7:0] mem_out;
    wire [7:0] ir_out;
    wire [7:0] a_out; // Register A output (final result for display)
    wire [7:0] b_out; // Register B output
    wire [7:0] alu_result;
    wire Z_flag, C_flag;
    wire [3:0] opcode;

    // --- Instantiate Clock Module (Modified) ---
    clock u_clock (
        .clk_100mhz (clk_in),
        .rst        (rst),      // Pass reset to clock module
        .hlt        (u_controller.hlt_ff), // Use the latched halt signal
        .step_in    (btn_step), // Connect step button
        .run_in     (btn_run),  // Connect run button
        .clk_out    (cpu_clk)   // Output is the controlled CPU clock
    );

    // --- Instantiate CPU Components (using cpu_clk) ---
    // NOTE: All synchronous components now use cpu_clk
    pc u_pc (.clk(cpu_clk), .rst(rst), .inc(pc_inc), .out(pc_out_internal));
    memory u_memory (.clk(cpu_clk), .rst(rst), .load(mar_load), .bus(bus_data), .out(mem_out));
    reg_a u_reg_a (.clk(cpu_clk), .rst(rst), .load(a_load), .bus(bus_data), .out(a_out));
    reg_b u_reg_b (.clk(cpu_clk), .rst(rst), .load(b_load), .bus(bus_data), .out(b_out));
    ir u_ir (.clk(cpu_clk), .rst(rst), .load(ir_load), .bus(bus_data), .out(ir_out));

    // *** Instantiate ALU (No clock needed - Combinational) ***
    alu u_alu (
        .in_a    (a_out),
        .in_b    (b_out),
        .op_sel  (alu_op_sel),
        .result  (alu_result),
        .Z_flag  (Z_flag),
        .C_flag  (C_flag)
    );

    // --- Instantiate Controller (using cpu_clk) ---
    assign opcode = ir_out[7:4];
    // Make sure the controller has the hlt_ff output exposed
    // (The provided controller.v already has this)
    controller u_controller (.clk(cpu_clk), .rst(rst), .opcode(opcode), .out(control_word));
    // Expose hlt_ff if needed for clock module: wire controller_hlt_ff = u_controller.hlt_ff; (Connect this to clock module hlt input)
    // The current code connects u_controller.hlt_ff directly, which is fine.

    // --- Deconstruct Control Word (14-bit) ---
    // No changes needed here
    assign hlt       = control_word[13]; // This is the COMBINATIONAL halt from the current state
                                         // The LATCHED halt (hlt_ff) is used for clock gating
    assign pc_inc    = control_word[12];
    assign pc_en     = control_word[11];
    assign mar_load  = control_word[10];
    assign mem_en    = control_word[9];
    assign ir_load   = control_word[8];
    assign ir_en     = control_word[7];
    assign a_load    = control_word[6];
    assign a_en      = control_word[5];
    assign b_load    = control_word[4];
    assign alu_en    = control_word[3];
    assign alu_op_sel= control_word[2:0];

    // --- Instantiate Bus Multiplexer (Combinational) ---
    bus_mux u_bus_mux (
        .alu_result(alu_result),
        .a_out(a_out), .ir_out(ir_out), .mem_out(mem_out), .pc_out(pc_out_internal),
        .alu_en(alu_en),
        .a_en(a_en), .ir_en(ir_en), .mem_en(mem_en), .pc_en(pc_en),
        .bus_data(bus_data)
    );

    // --- Instantiate Display Logic ---
    wire [3:0] bcd_h_w, bcd_t_w, bcd_o_w;
    // BCD converter is combinational, always reflects a_out
    binary_to_bcd u_bin_to_bcd (
        .bin_in       (a_out), // Input is the *current* result from Register A
        .bcd_hundreds (bcd_h_w),
        .bcd_tens     (bcd_t_w),
        .bcd_ones     (bcd_o_w)
    );

    // Display controller uses the FAST clock for refresh
    // *** CHANGED ENABLE SIGNAL ***
    seven_segment_controller u_display_controller (
        .clk      (clk_in),   // Use the fast main clock for refresh
        .reset    (rst),
        .enable   (1'b1),     // Display is ALWAYS enabled (unless reset)
                               // Alternative: .enable(~rst)
        .bcd_h    (bcd_h_w),
        .bcd_t    (bcd_t_w),
        .bcd_o    (bcd_o_w),
        .seg_out  (seg_out),
        .an_out   (an_out)
    );

    // --- Assign Top-Level Outputs ---
    assign hlt_out = u_controller.hlt_ff; // Output the latched halt status

endmodule
